-- MySQL Script generated by MySQL Workbench
-- Wed 20 May 2020 10:15:51 PM CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SAES
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SAES
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SAES` DEFAULT CHARACTER SET utf8 ;
USE `SAES` ;

-- -----------------------------------------------------
-- Table `SAES`.`Materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAES`.`Materia` (
  `Clave` VARCHAR(10) NOT NULL DEFAULT '',
  `Periodo` INT NOT NULL,
  `Nombre` VARCHAR(60) NOT NULL,
  `Tipo` VARCHAR(15) NOT NULL,
  `Creditos` FLOAT NOT NULL,
  PRIMARY KEY (`Clave`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAES`.`Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAES`.`Alumno` (
  `Boleta` VARCHAR(10) NOT NULL,
  `Nombre` VARCHAR(80) NULL,
  PRIMARY KEY (`Boleta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAES`.`Grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAES`.`Grupo` (
  `Grupo` VARCHAR(10) NOT NULL,
  `Materia_Clave` VARCHAR(10) NOT NULL,
  `Profesor` VARCHAR(80) NULL,
  `Turno` VARCHAR(4) NULL,
  `Ocupabilidad` INT NULL,
  PRIMARY KEY (`Grupo`, `Materia_Clave`),
  INDEX `fk_Grupo_2_idx` (`Materia_Clave` ASC),
  CONSTRAINT `fk_Grupo_2`
    FOREIGN KEY (`Materia_Clave`)
    REFERENCES `SAES`.`Materia` (`Clave`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAES`.`Clases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAES`.`Clases` (
  `Grupo` VARCHAR(10) NOT NULL,
  `Materia_Clave` VARCHAR(45) NOT NULL,
  `Dia` VARCHAR(10) NOT NULL,
  `Hora` VARCHAR(15) NULL,
  PRIMARY KEY (`Grupo`, `Materia_Clave`, `Dia`),
  INDEX `fk_Clases_1_idx` (`Grupo` ASC),
  INDEX `fk_Clases_2_idx` (`Materia_Clave` ASC),
  CONSTRAINT `fk_Clases_1`
    FOREIGN KEY (`Grupo`)
    REFERENCES `SAES`.`Grupo` (`Grupo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Clases_2`
    FOREIGN KEY (`Materia_Clave`)
    REFERENCES `SAES`.`Materia` (`Clave`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAES`.`Horarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAES`.`Horarios` (
  `ID_Horario` VARCHAR(200) NOT NULL,
  `Alumno_Boleta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Horario`, `Alumno_Boleta`),
  INDEX `fk_Horarios_1_idx` (`Alumno_Boleta` ASC),
  CONSTRAINT `fk_Horarios_1`
    FOREIGN KEY (`Alumno_Boleta`)
    REFERENCES `SAES`.`Alumno` (`Boleta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAES`.`Temporal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAES`.`Temporal` (
  `Materia_Clave` VARCHAR(10) NOT NULL,
  `Alumno_Boleta` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Materia_Clave`, `Alumno_Boleta`),
  INDEX `fk_Temporal_2_idx` (`Alumno_Boleta` ASC),
  CONSTRAINT `fk_Temporal_1`
    FOREIGN KEY (`Materia_Clave`)
    REFERENCES `SAES`.`Materia` (`Clave`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Temporal_2`
    FOREIGN KEY (`Alumno_Boleta`)
    REFERENCES `SAES`.`Alumno` (`Boleta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAES`.`Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAES`.`Horario` (
  `ID` VARCHAR(200) NOT NULL,
  `Materia_Clave` VARCHAR(10) NOT NULL,
  `Grupo` VARCHAR(10) NULL,
  PRIMARY KEY (`ID`, `Materia_Clave`),
  INDEX `fk_Horario_1_idx` (`Materia_Clave` ASC),
  CONSTRAINT `fk_Horario_1`
    FOREIGN KEY (`Materia_Clave`)
    REFERENCES `SAES`.`Materia` (`Clave`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Horario_2`
    FOREIGN KEY (`ID`)
    REFERENCES `SAES`.`Horarios` (`ID_Horario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
